# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]

required = [

# 제네레이터 사용 - db, session 에서 사용
"github.com/bwmarrin/snowflake",

# 세션 메모리 스토어가 사용
"github.com/patrickmn/go-cache",
#test
"github.com/PuerkitoBio/goquery",

#auth
"github.com/casbin/casbin",
#DB
"github.com/jinzhu/gorm",

#render
"github.com/ezaurum/boongeoppang",

# echo
"github.com/labstack/echo",

#gin
  "github.com/gin-gonic/gin"
]
