# dev stack 개발용
# Run 도커 stack 으로 실행
# docker stack deploy -c dev-stack.yml mysql
# or 도커 컴포즈로 실행
# docker-compose -f dev-stack.yml up

version: "3.7"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: devp
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
     - --skip-character-set-client-handshake
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    expose:
      - 3306
